"""empty message

Revision ID: 763fb5ea7ca6
Revises: 99e1b0160576
Create Date: 2023-05-10 23:04:08.187895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '763fb5ea7ca6'
down_revision = '99e1b0160576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_email_key', type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('user_email_key', ['email'])

    # ### end Alembic commands ###
